// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABKCxiu17PBwyDQm52jNDM7CkoOF9UxA',
    appId: '1:544016935933:android:16ef0ee654a254fa888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIE38i8tKG-MPOCc7MzL-TNKN0-imb7UY',
    appId: '1:544016935933:ios:7d8f941e4297affb888794',
    messagingSenderId: '544016935933',
    projectId: 'laundary-app-272a6',
    databaseURL: 'https://laundary-app-272a6-default-rtdb.firebaseio.com',
    storageBucket: 'laundary-app-272a6.firebasestorage.app',
    iosBundleId: 'com.fastlaundry.deliveryapp',
  );
}
